default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000


test:
  <<: *default
  database: aircall_test

development:
  <<: *default
  database: aircall_development

production:
  <<: *default
  database: aircall_production
  username: <%= ENV['AIRCALL_PRODUCTION_USERNAME'] %>
  password: <%= ENV['AIRCALL_PRODUCTION_PWD'] %>
